import Coffee from '@/components/core/Coffee';
import Icon from '@/components/core/Icon';
import packageJson from '@/package.json';

export default function SettingsInfo() {
  const email = 'csr.maeum.me@gmail.com';
  const kakao = 'https://open.kakao.com/o/sa4PxhCg';
  const form = 'https://forms.gle/8L5ZQJjBAdaqxj366';
  const dependencies = Object.keys(packageJson.dependencies);

  return (
    <div className="flex flex-col gap-32">
      <a
        href="https://x.com/ma_eum_me"
        target="_blank"
        className="flex items-center gap-8 self-start rounded-8 bg-gray-50 px-16 py-12"
      >
        <Icon type="twitter" className="w-18 text-gray-500" />
        <div className="text-16 font-600 text-black">@ma_eum_me</div>
      </a>

      <div className="flex flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">Contact</div>
        <div className="flex flex-col gap-4 text-16 font-400 text-black">
          <div>
            Email:{' '}
            <a href={`mailto:${email}`} className="text-primary-500 underline">
              {email}
            </a>
          </div>
          <div>
            Kakao:{' '}
            <a href={kakao} target="_blank" className="text-primary-500 underline">
              {kakao}
            </a>
          </div>
          <div>
            Form:{' '}
            <a href={form} target="_blank" className="text-primary-500 underline">
              {form}
            </a>
          </div>
        </div>
      </div>

      <div className="flex flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">Repository</div>
        <div className="flex flex-col gap-4 text-16 font-400 text-black">
          <div>
            Github:{' '}
            <a
              href="https://github.com/delta-kor/ma-eum"
              target="_blank"
              className="text-primary-500 underline"
            >
              delta-kor/ma-eum
            </a>
          </div>
        </div>
        <div className="flex flex-col gap-4 text-16 font-400 text-black">
          This project is completely open-source, permitting unrestricted modification,
          reproduction, and distribution without the need for further permission.
        </div>
      </div>

      <div className="flex flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">Disclaimer</div>
        <div className="flex flex-col gap-12 text-16 font-400 text-black">
          <div>
            This website is a fan-website of CSR and{' '}
            <span className="font-600 underline">is not an official website.</span>
          </div>
          <div>
            This website does not represent the official position of CSR and its related companies.
          </div>
        </div>
      </div>

      <div className="flex flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">AI Contents</div>
        <div className="flex flex-col gap-12 text-16 font-400 text-black">
          <div>This website may contain content created by AI or other automated technologies.</div>
          <div>Followings are partially generated by AI:</div>
          <div className="pl-16">- Landing page banner</div>
        </div>
      </div>

      <div className="flex flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">Copyrights</div>
        <div className="flex flex-col gap-12 text-16 font-400 text-black">
          <div>
            This website may contain copyrighted content for non-profit use. Every copyrighted
            content is provided with external link of its original form.
          </div>
          <div>
            All rights and credit go directly to its rightful owner(s). No copyright infringement
            intended.
          </div>
          <div className="font-600">Takedown request: {email}</div>
        </div>
      </div>

      <div className="flex max-w-screen-sm flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">Open Source License</div>
        <div className="grid grid-cols-2 gap-4 text-16 font-400 text-black">
          {dependencies.map(dependency => (
            <a
              key={dependency}
              href={`https://npmjs.com/package/${dependency}`}
              target="_blank"
              className="truncate"
            >
              {dependency}
            </a>
          ))}
        </div>
      </div>

      <div className="flex max-w-screen-sm flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">Shipped on</div>
        <div className="flex flex-col gap-4 text-16 font-400 text-black">
          <div>Vercel: sin1/ap-southeast-1 (Singapore) / Edge</div>
          <div>Upstash: sin1/ap-southeast-1 (Singapore)</div>
          <div>Neon: Asia Pacific (Singapore)</div>
          <div>Gcloud: 가산IDC LG U+/KINX (South Korea)</div>
        </div>
      </div>

      <div className="flex max-w-screen-sm flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">Kickstarted on</div>
        <div className="flex flex-col gap-4 text-16 font-400 text-black">
          <div>2024. 5. 19.</div>
        </div>
      </div>

      <div className="flex max-w-screen-sm flex-col gap-10">
        <div className="text-18 font-700 text-primary-500">Released on</div>
        <div className="flex flex-col gap-4 text-16 font-400 text-black">
          <div>2024. 7. 27.</div>
        </div>
      </div>

      <Coffee />

      <div className="h-1 self-stretch bg-gray-100" />

      <div className="flex flex-col items-center gap-24 md:grid md:grid-cols-2">
        <div className="flex w-full flex-col gap-12">
          <iframe
            allow="autoplay; fullscreen; picture-in-picture; clipboard-write"
            frameBorder="0"
            src="https://player.vimeo.com/video/990549120?title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
            title="CSR 2nd Anniversary"
            className="aspect-video w-full"
          ></iframe>
          <div className="flex flex-col gap-4">
            <div className="text-18 font-600 text-gray-500">CSR 2nd Anniversary</div>
            <div className="text-16 font-500 text-gray-200">S. Y. Sohn / H. Y. Kwon</div>
          </div>
        </div>
        <div className="flex w-full flex-col gap-12">
          <iframe
            allow="autoplay; fullscreen; picture-in-picture; clipboard-write"
            frameBorder="0"
            src="https://player.vimeo.com/video/990228360?title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
            title="[Final] maeum.me launch trailer"
            className="aspect-video w-full"
          ></iframe>
          <div className="flex flex-col gap-4">
            <div className="text-18 font-600 text-gray-500">maeum.me Launch Trailer</div>
            <div className="text-16 font-500 text-gray-200">J. S. Lee / E. S. Kim / S. Y. Sohn</div>
          </div>
        </div>
      </div>

      <div className="h-1 self-stretch bg-gray-100" />
      <div className="flex flex-col gap-4">
        <div className="text-16 font-500 italic text-gray-500">Crafted by,</div>
        <div className="text-18 font-700 text-gray-500">msqr labs</div>
      </div>

      <div className="text-16 font-500 text-gray-200">Made with ♥ in Korea</div>
    </div>
  );
}
